# Generated by Django 5.1.2 on 2024-10-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='volunteers',
            field=models.ManyToManyField(to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
