# Generated by Django 5.1.2 on 2024-10-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_clothingdonation_donor_alter_donation_donor_and_more'),
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='MonetaryDonation',
        ),
    ]
